<h1>数据格式说明<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Index" data-toc-modified-id="Index-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Index</a></span></li><li><span><a href="#userEventScores" data-toc-modified-id="userEventScores-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>userEventScores</a></span></li><li><span><a href="#User&lt;=&gt;events" data-toc-modified-id="User<=>events-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>User&lt;=&gt;events</a></span></li><li><span><a href="#uniquePairs" data-toc-modified-id="uniquePairs-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>uniquePairs</a></span></li><li><span><a href="#eventMatrix" data-toc-modified-id="eventMatrix-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>eventMatrix</a></span></li><li><span><a href="#eventSim" data-toc-modified-id="eventSim-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>eventSim</a></span></li><li><span><a href="#userMatrix&amp;Sim" data-toc-modified-id="userMatrix&amp;Sim-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>userMatrix&amp;Sim</a></span></li><li><span><a href="#userFriends" data-toc-modified-id="userFriends-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>userFriends</a></span></li><li><span><a href="#eventPopularity" data-toc-modified-id="eventPopularity-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>eventPopularity</a></span></li></ul></div>

In [2]:
import scipy.io as siopei'x
import scipy.sparse as ss
import pickle

In [3]:
# sio.mmread("PE_userEventScores")    
# pickle.load(open("PE_eventsForUser.pkl", 'rb'))

In [4]:
# 数据地址
dpath = 'E:/AI/00/data/EventRecommendation/'

# Index

In [7]:
#保存用户索引表
userIndex  = pickle.load(open(dpath+"PE_userIndex.pkl", 'rb'))
#保存活动索引表
eventIndex = pickle.load(open(dpath+"PE_eventIndex.pkl", 'rb'))
print('len  is:', len(userIndex),  len(eventIndex))
print('type is:', type(userIndex), type(eventIndex))

len is: 3391 13418
type is: <class 'dict'> <class 'dict'>


In [8]:
userIndex

{'1427469971': 0,
 '3231004341': 1,
 '3799386472': 2,
 '67249956': 3,
 '1804164018': 4,
 '2683024755': 5,
 '4205046694': 6,
 '1354531726': 7,
 '4238211626': 8,
 '3198320860': 9,
 '305160382': 10,
 '3199368063': 11,
 '3598881287': 12,
 '694221975': 13,
 '583119832': 14,
 '3803199563': 15,
 '23170479': 16,
 '283716061': 17,
 '7514340': 18,
 '2065629938': 19,
 '1757951758': 20,
 '995064362': 21,
 '422699736': 22,
 '2259554717': 23,
 '3601181201': 24,
 '4162525077': 25,
 '1428101175': 26,
 '2040340167': 27,
 '4275037038': 28,
 '2399006053': 29,
 '3042642967': 30,
 '4246010516': 31,
 '1935886581': 32,
 '531967718': 33,
 '2724319931': 34,
 '892435980': 35,
 '2766172404': 36,
 '973677184': 37,
 '1235578437': 38,
 '428619631': 39,
 '85640691': 40,
 '763143562': 41,
 '3627571763': 42,
 '1739369956': 43,
 '3141270743': 44,
 '983894136': 45,
 '3316923302': 46,
 '1116289197': 47,
 '3705805946': 48,
 '639250885': 49,
 '2706381153': 50,
 '2090888096': 51,
 '1649320589': 52,
 '1489351479': 53,
 '1879

In [9]:
eventIndex

{'3429610508': 0,
 '3084982208': 1,
 '3542590909': 2,
 '3164534147': 3,
 '1886452892': 4,
 '981308672': 5,
 '3288255289': 6,
 '2654849737': 7,
 '3632090303': 8,
 '498959605': 9,
 '1916133216': 10,
 '2319080380': 11,
 '1325647788': 12,
 '1516820536': 13,
 '3280467847': 14,
 '2233985749': 15,
 '2642751886': 16,
 '2331092173': 17,
 '3838537047': 18,
 '524333092': 19,
 '2762265640': 20,
 '3412307751': 21,
 '2695471827': 22,
 '2892792634': 23,
 '3074569974': 24,
 '2531947768': 25,
 '1044974227': 26,
 '1545807185': 27,
 '3856018417': 28,
 '3759077194': 29,
 '1344296761': 30,
 '1550429882': 31,
 '2379329185': 32,
 '3174718152': 33,
 '4267881656': 34,
 '431193333': 35,
 '2796556769': 36,
 '2663748542': 37,
 '489711508': 38,
 '1294481466': 39,
 '69233369': 40,
 '4225044675': 41,
 '1611840162': 42,
 '897667289': 43,
 '1181449211': 44,
 '3565166403': 45,
 '3981007415': 46,
 '4289884077': 47,
 '4215548909': 48,
 '1512603079': 49,
 '1841631859': 50,
 '2509151803': 51,
 '1462062430': 52,
 '157745330

# userEventScores

In [14]:
#用户-活动关系矩阵
#得分为0,不感兴趣; 得分为1,有兴趣
userEventScores = sio.mmread(dpath+"PE_userEventScores")
print('type  is:',type(userEventScores))
print('shape is:',userEventScores.shape)

type  is: <class 'scipy.sparse.coo.coo_matrix'>
shape is: (3391, 13418)


In [49]:
userEventScores.getrow(3333).todense()

matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [41]:
print(userEventScores.getrow(3333))
#getrow( userIndex[]) == 1
#代表user对哪些eventIndex[]感兴趣

  (0, 9761)	1.0
  (0, 3343)	1.0


In [43]:
print(userEventScores.getcol(3343))
#getcol(eventIndex[]) == 1
#表示该event有哪些userIndex[]感兴趣

  (3333, 0)	1.0


In [45]:
print(userEventScores.getrow(3333).getcol(3343))
#getrow(userIndex[]).getcol(eventIndex[])==1
#表示该userIndex对该eventIndex感兴趣

  (0, 0)	1.0


# User<=>events

In [45]:
print(userEventScores.getrow(3333).getcol(3343))

  (0, 0)	1.0


In [60]:
#读数据
usersForEvent = pickle.load(open(dpath+"PE_usersForEvent.pkl", 'rb'))
eventsForUser = pickle.load(open(dpath+"PE_eventsForUser.pkl", 'rb'))
print('len  is:', len(usersForEvent),  len(eventsForUser))
print('type is:', type(usersForEvent), type(eventsForUser))

len  is: 8846 2034
type is: <class 'collections.defaultdict'> <class 'collections.defaultdict'>


In [62]:
eventsForUser
#{userIndex[]: eventIndex[]***}

defaultdict(set,
            {1033: {288, 637, 1374, 1747, 9878, 9892},
             127: {1978, 2412, 3792, 11139, 11650, 11751, 11956},
             1490: {2363, 2662, 3527, 3914, 5785, 11671},
             9: {6484, 6504, 7882, 10507, 11684, 13180},
             2470: {1177, 3138, 6252, 10492, 12574, 12968},
             625: {220,
              2563,
              2668,
              2971,
              3259,
              5317,
              5814,
              6131,
              6647,
              8231,
              8845,
              9173,
              11835,
              12715},
             1415: {2806, 4312, 4803, 4815, 5271, 11902},
             2825: {35, 3724, 4823, 4844, 8676, 9173},
             3060: {4310, 4680, 7727, 9146, 9998, 10311, 10945},
             1947: {916, 924, 4951, 5121, 5714, 10503},
             1131: {83, 3035, 3185, 3376, 9504, 11308},
             873: {6463, 7603, 11291, 12889, 13067, 13315},
             2580: {261, 2915, 4868, 5972, 9396, 1

In [63]:
usersForEvent
#{eventIndex[]: userIndex[]***}}

defaultdict(set,
            {9892: {1033, 1555},
             288: {224, 411, 1033, 1079},
             637: {21,
              22,
              33,
              74,
              81,
              88,
              93,
              116,
              123,
              148,
              151,
              197,
              224,
              235,
              239,
              261,
              263,
              297,
              308,
              329,
              333,
              350,
              387,
              403,
              411,
              426,
              438,
              444,
              459,
              464,
              507,
              508,
              534,
              575,
              630,
              631,
              642,
              650,
              666,
              689,
              711,
              746,
              747,
              755,
              758,
              760,
              764,
              769

# uniquePairs

In [54]:
#读数据
uniqueUserPairs  = pickle.load(open(dpath+"FE_uniqueUserPairs.pkl",  'rb'))
uniqueEventPairs = pickle.load(open(dpath+"PE_uniqueEventPairs.pkl", 'rb'))
print('len  is:', len(uniqueUserPairs),  len(uniqueEventPairs))
print('type is:', type(uniqueUserPairs), type(uniqueEventPairs))

len  is: 81001 57638
type is: <class 'set'> <class 'set'>


In [67]:
i=0
for u in uniqueUserPairs:
    print('uniqueUserPairs :',u)
    i+=1
    if i==10:break
#(userIndex[],userIndex[]) in uniqueUserPairs
#表示两个user都对至少某一event感兴趣

uniqueUserPairs : (1497, 3101)
uniqueUserPairs : (199, 495)
uniqueUserPairs : (1454, 3269)
uniqueUserPairs : (3182, 3262)
uniqueUserPairs : (2453, 1659)
uniqueUserPairs : (116, 1471)
uniqueUserPairs : (1822, 297)
uniqueUserPairs : (1967, 1344)
uniqueUserPairs : (2053, 2317)
uniqueUserPairs : (171, 86)


In [68]:
i=0
for e in uniqueEventPairs:
    print('uniqueEventPairs :',e)
    i+=1
    if i==10:break
#(eventIndex[],eventIndex[]) in uniqueEventPairs
#表示两个event都曾被同一user参加过

uniqueEventPairs : (3589, 9534)
uniqueEventPairs : (1961, 8845)
uniqueEventPairs : (12999, 4366)
uniqueEventPairs : (901, 6047)
uniqueEventPairs : (5558, 5303)
uniqueEventPairs : (4933, 5802)
uniqueEventPairs : (776, 11671)
uniqueEventPairs : (130, 1042)
uniqueEventPairs : (1606, 12903)
uniqueEventPairs : (10036, 3480)


# eventMatrix

In [69]:
#eventPropMatrix : start_time, city, state, zip, country, lat, and lng
#eventContMatrix : 101 columns of words count
#都经过特征工程, 以及normalize
eventPropMatrix = sio.mmread(dpath+"EV_eventPropMatrix")
eventContMatrix = sio.mmread(dpath+"EV_eventContMatrix")
print('type  is:',type(eventPropMatrix), type(eventContMatrix))
print('shape is:',eventPropMatrix.shape, eventContMatrix.shape)

type  is: <class 'scipy.sparse.coo.coo_matrix'> <class 'scipy.sparse.coo.coo_matrix'>
shape is: (13418, 7) (13418, 101)


In [70]:
eventPropMatrix.getrow(0).todense()

matrix([[  8.84406971e-03,  -2.84560901e-07,  -3.44445933e-07,
          -6.96408464e-07,  -3.66193966e-07,   0.00000000e+00,
           0.00000000e+00]])

In [71]:
eventContMatrix.getrow(0).todense()

matrix([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.00931574,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.

# eventSim

In [72]:
#eventPropMatrix : start_time, city, state, zip, country, lat, and lng
#eventContMatrix : 101 columns of words count
#非词频特征，采用Person相关系数作为相似度
#对词频特征，采用余弦相似度，也可以用直方图交/Jacard相似度
eventPropSim = sio.mmread(dpath+"EV_eventPropSim")
eventContSim = sio.mmread(dpath+"EV_eventContSim")
print('type  is:',type(eventPropSim), type(eventContSim))
print('shape is:',eventPropSim.shape, eventContSim.shape)

type  is: <class 'scipy.sparse.coo.coo_matrix'> <class 'scipy.sparse.coo.coo_matrix'>
shape is: (13418, 13418) (13418, 13418)


In [91]:
print(eventPropSim.getrow(3343))
#getrow(eventIndex[])
#代表该eventIndex[]与哪些eventIndex[]相似
#值代表相似度是多少

  (0, 9761)	0.000749416807861
  (0, 6413)	0.289408871986
  (0, 4580)	0.0529147507993
  (0, 3726)	0.088683453459
  (0, 287)	0.808298848504


In [81]:
print(eventContSim.getrow(3343))
#getrow(eventIndex[])
#代表该eventIndex[]与哪些eventIndex[]相似
#值代表相似度是多少

  (0, 9761)	0.000749416807861
  (0, 6413)	0.289408871986
  (0, 4580)	0.0529147507993
  (0, 3726)	0.088683453459
  (0, 287)	0.808298848504


In [92]:
print(eventPropSim.getrow(3343).getcol(287))
#getrow(eventIndex[]).getcol(eventIndex[])
#代表该eventIndex[]与另一eventIndex[]相似
#值代表相似度是多少

  (0, 0)	0.808298848504


# userMatrix&Sim

In [5]:
#elocale, birthyear, gender, joinedAt, location, timezone
#去掉user_id列, 特征编码且normalize后为 userMatrix
userMatrix = sio.mmread(dpath+"US_userMatrix")
#计算用户相似度矩阵, 对称矩阵, 对角线为1(自己与自己)
#Person相关系数做为相似度度量
userSimMatrix = sio.mmread(dpath+"US_userSimMatrix")
print('type  is:',type(userMatrix), type(userSimMatrix))
print('shape is:',userMatrix.shape, userSimMatrix.shape)

type  is: <class 'scipy.sparse.coo.coo_matrix'> <class 'scipy.sparse.coo.coo_matrix'>
shape is: (3391, 6) (3391, 3391)


In [98]:
print(userMatrix.getrow(123))
#getrow(userIndex[])
#userIndex[]对应的编码后的特征

  (0, 5)	0.0182439887525
  (0, 4)	0.0249528815063
  (0, 3)	0.0171982628335
  (0, 2)	0.0119625441007
  (0, 1)	0.0172610220468
  (0, 0)	0.0216288560856


In [111]:
print(userSimMatrix.getrow(123))
#getrow(userIndex[])
#代表该userIndex[]与哪些userIndex[]相似
#值代表相似度是多少

  (0, 3378)	5.04754171582e-06
  (0, 3370)	1.36477257717
  (0, 3361)	1.13620418294e-05
  (0, 3329)	2.83860437911e-06
  (0, 3300)	0.920159484897
  (0, 3293)	0.0272252573551
  (0, 3283)	0.753511914228
  (0, 3261)	0.753424241222
  (0, 3241)	5.04754171582e-06
  (0, 3236)	1.54684335524e-05
  (0, 3230)	1.261317365e-06
  (0, 3229)	0.753366959516
  (0, 3227)	0.753094387899
  (0, 3224)	1.54684335524e-05
  (0, 3223)	0.753395484043
  (0, 3218)	1.75653714629
  (0, 3206)	1.54684335524e-05
  (0, 3177)	2.83860437911e-06
  (0, 3176)	2.0208133475e-05
  (0, 3161)	1.36819033453
  (0, 3147)	7.8885488215e-06
  (0, 3143)	3.15114261351e-07
  (0, 3141)	5.04754171582e-06
  (0, 3134)	0.00400611115963
  (0, 3119)	7.8885488215e-06
  :	:
  (0, 263)	1.36825788082
  (0, 261)	7.8885488215e-06
  (0, 239)	1.36822414812
  (0, 235)	0.687102923328
  (0, 227)	0.755811292039
  (0, 224)	0.335400663178
  (0, 214)	5.04754171582e-06
  (0, 213)	2.83860437911e-06
  (0, 197)	0.75348245576
  (0, 185)	1.13620418294e-05
  (0, 171)	2.8

In [113]:
print(userSimMatrix.getrow(123).getcol(3161))
#getrow(userIndex[]).getcol(userIndex[])
#代表该userIndex[]与另一userIndex[]相似
#值代表相似度是多少

  (0, 0)	1.36819033453


# userFriends

In [114]:
#归一化后的朋友的数目
numFriends = sio.mmread(dpath+"UF_numFriends")
#所有朋友参加活动的数量（平均频率）
#对称矩阵
userFriends = sio.mmread(dpath+"UF_userFriends")
print('type  is:',type(numFriends), type(userFriends))
print('shape is:',numFriends.shape, userFriends.shape)

type  is: <class 'numpy.ndarray'> <class 'scipy.sparse.coo.coo_matrix'>
shape is: (1, 3391) (3391, 3391)


In [121]:
print(numFriends[:,123])
#numFriends[:,userIndex[]]
#该user拥有的朋友的数量

[ 0.00096506]


In [122]:
print(userFriends.getrow(123))
#getrow(userIndex[])
#代表该userIndex[]有哪些朋友
#值代表朋友参加活动的数量

  (0, 2568)	0.316227766017
  (0, 1467)	0.565685424949
  (0, 937)	1.0
  (0, 197)	0.279836623104


# eventPopularity

In [126]:
#归一化后的活动的热度(参加人数的多少)
eventPopularity = sio.mmread(dpath+"EA_eventPopularity")
print('type  is:',type(eventPopularity))
print('shape is:',eventPopularity.shape)

type  is: <class 'scipy.sparse.coo.coo_matrix'>
shape is: (13418, 1)


In [129]:
print(eventPopularity.getrow(123))
#getrow(eventIndex[])
#代表该eventIndex[]有哪些user参加
#值代表参加event的user的数量

  (0, 0)	8.7419625706e-05
